const pageTheme = [
  {
    url: 'http://consumerapp-1251779293.file.myqcloud.com/discovery/201910/ahwir8ar5f.png?imageView2/2/w/240',
    title: '专题页',
    data: '{"body":{"style":{"background-color":"#fff"}},"pages":[{"id":1,"name":"页面1","content":[{"name":"专题菜单","tag":"menus","theme":1,"dataType":0,"singleDatas":{"checkedId":1,"data":[{"checkedId":1,"name":"新人指引","action":{}},{"checkedId":2,"name":"取件通知","action":{}},{"checkedId":3,"name":"收件篇","action":{}},{"checkedId":4,"name":"老司机经验","action":{}}]},"heightType":"set","moduleHeight":50,"moduleStyle":{"padding-left":10,"padding-right":10},"itemStyle":{},"checkedBarStyle":{"width-percent":70,"height":3,"border-radius":3,"background-color":"#9AD708"},"checkedBarPosStyle":{"text-align":"center","bottom":5},"contentPaddingRight":10,"nameStyle":{"font-size":14,"color":"#999999","line-height":30,"padding-left":10,"padding-right":10,"padding-top":5,"padding-bottom":5},"nameCheckedStyle":{"font-size":16,"color":"#4A4A4A"},"id":"1282011482"},{"name":"专题列表","tag":"group","theme":3,"dataType":0,"singleDatas":{"data":[{"url":"http://consumerapp-1251779293.image.myqcloud.com/discovery/201910/2698iqkw97v.png","title":"丰巢智能柜-派件篇","description":"2019-10-21","action":{}},{"url":"http://consumerapp-1251779293.image.myqcloud.com/discovery/201910/2698iqkw97v.png","title":"丰巢智能柜-派件篇","description":"2019-10-21","action":{}}]},"moduleStyle":{"padding-top":16,"padding-left":16,"padding-right":16},"imageStyle":{},"titleStyle":{"font-size":16,"color":"#4A4A4A"},"descriptionStyle":{"font-size":12,"color":"#999999"},"id":"1488820557","heightType":"auto","moduleHeight":230}],"style":{"background-color":"","background-position":"top","background-repeat":"repeat"},"isTab":0}],"pops":[{"id":1,"name":"弹窗1","elements":[]}]}'
  },
  {
    url: 'http://consumerapp-1251779293.file.myqcloud.com/discovery/201910/49bkwxpigga.png?imageView2/2/w/240',
    title: '文章页',
    data: '{"body":{"style":{"background-color":"#fff"}},"pages":[{"id":1,"name":"页面1","content":[{"name":"文章信息","tag":"group","theme":4,"title":"文章标题","author":"作者","time":"2019-10-21 14:00:00","moduleStyle":{"padding-top":16,"padding-left":16,"padding-right":16,"padding-bottom":16},"titleStyle":{"font-size":18,"font-weight":500,"line-height":24,"color":"#4A4A4A"},"id":"1267969279","heightType":"auto","moduleHeight":82},{"name":"文章内容","tag":"images","theme":1,"dataType":0,"singleDatas":{"data":[{"url":"http://consumerapp-1251779293.image.myqcloud.com/discovery/201910/ewbz314e1he.png","title":"十三能织素，十四学裁衣，十五弹箜篌，十六诵诗书。十七为君妇，心中常苦悲。君既为府吏，守节情不移，贱妾留空房，相见常日稀。鸡鸣入机织，夜夜不得息。三日断五匹，大人故嫌迟。非为织作迟，君家妇难为！妾不堪驱使，徒留无所施，便可白公姥，及时相遣归。","description":"","action":{}}]},"contentPaddingBottom":16,"moduleStyle":{"padding-left":16,"padding-right":16},"itemStyle":{},"imageStyle":{},"titleStyle":{"font-size":14,"color":"#333333","line-height":24,"padding-top":16},"descriptionStyle":{},"id":"1046573281","heightType":"auto","moduleHeight":348}],"style":{"background-color":"","background-position":"top","background-repeat":"repeat"},"isTab":0}],"pops":[{"id":1,"name":"弹窗1","elements":[]}]}'
  }
]
export default pageTheme
